@plr = player()


@hero = associative_array(
            'name': '§l§0Ma§4dra§0kk',
            'class': 'mandrakk',
            'sig': 'qJnwp7cKPtxTDmfZXLFKR/vOCVKoyu3KMFPpcbzQ6EfO/mUhK5hKbMF0GB7qB/q6MLVZflJRjWBlciXtuvAt1DJLvM3qPe8GIIenbOIzNyfDIjhuK9SDeIyAuSjjbfAdyIhFk+eSFLOYgqsz98Afv5n+z6t+R3cvOJc22/kBf8iyS2uwplkY/dbKeGNevC1XgiHGXvKnSSwPShtdgQ3Od/cB2JXD/dy79mDgG3WQCblilyu+ox+FZB93p+U5epnRRixVgDTlKgyi6HS3YtMZGesurMaz/uO+QcIQbiHbipR+hpvXIUkvS8pMi06izJVYrOuE8BmEcoEru28WvJI+czAgmrlq4cqtHlH3LaQRMi6GwKXauFrou8diiKVVgSRF/DJDZWa1B1CEAvVhEwsChz3NSdFYGq4zH1piRpwOb9pueiM7CoWZfDO9ZILXgz9uiDTtLtE2iof+t3vbVAMKuGScOi68bIiciyooaJVtfcUUt+NiGVYrpMINxx7G22sd0FLQVLQ7ZPSjNOBFzJQd5X7g7uvbj56Nn0qgfxMtLUgDCV66XDlPhb5yRzBtSi2BvyO04GtRMV8FWTQcEWwEDG6YV0RrO1MZB5YH9W34sE9g6zueAQpP+p8wx2aVVovd0IzNbe+N9ThfOYM4s8AHDDf4Ffw5uxafvOS86si8B98=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0ODM3NDAyNjI4MjcsInByb2ZpbGVJZCI6IjBlNDJlNDc0MTM0ODRmYTg5N2M2Y2IzOWE5YzA5ODhmIiwicHJvZmlsZU5hbWUiOiJjYXJkaGFkeSIsInNpZ25hdHVyZVJlcXVpcmVkIjp0cnVlLCJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmJmNDU1N2FkNDc3MjdlNTRhMmZhNjQ4MjQ1ZmU1MWQ5ZmM1N2E4Y2RkMjA0NGZhNmNiZmEwZDA3NTk2MTMifX19',
            'trail': '',
            'op': 'false',
            'speech': "I will drain everything!",
            'powers': array(
                "/buff",
                "/carryplayer",
                "/dismountplayer",
                "/flyspeed <number>",
                "/run 0-9",
                "/back",
                "/tppos <x> <y> <z>",
                "/tp",
                "Access to all warps"
                "/fly"
            ),
            'buffs': array(
                "/effect ". @plr ." 5 9999 25 true",
                "/effect ". @plr ." 11 9999 3 true",
                "/effect ". @plr ." 12 9999 1 true",
                "/effect ". @plr ." 16 9999 1 true",
                "/effect ". @plr ." 21 9999 19 true",
                "/shot give ". @plr ."energybeam",
                "/shot give ". @plr ."dimensionalbeam",                
            )
        )
